package dev.nazhida.kivra.admin;

import dev.nazhida.kivra.Kivra;
import dev.nazhida.kivra.integration.WanderlogIntegration;
import dev.nazhida.kivra.moderation.ModerationService.Record;
import dev.nazhida.kivra.permissions.PermissionGroup;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.SimpleMenuProvider;
import net.minecraft.world.inventory.ChestMenu;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import java.math.BigDecimal;
import java.util.*;

public final class AdminMenuEvents {
 private static final Map<UUID,String> CONFIRM=new HashMap<>();
 public static void handleClick(ServerPlayer v,ItemStack c){if(!admin(v)){v.closeContainer();say(v,"You no longer have permission to use Kivra Admin.");return;}if(c.isEmpty()||!c.hasTag())return;String a=c.getOrCreateTag().getString("KivraAdminAction");if(a.isBlank()||a.equals("noop"))return;
  if(a.equals("Players")){openPlayers(v);return;}if(a.equals("Ranks & Permissions")){openRanksOverview(v);return;}if(a.equals("Economy")){openEconomy(v);return;}if(a.equals("Claims")){openClaims(v);return;}if(a.equals("Shops")){openShops(v);return;}if(a.equals("Kits")){openKits(v);return;}if(a.equals("Moderation")){openModeration(v);return;}if(a.equals("Wanderlog")){openWanderlog(v);return;}if(a.equals("Close")||a.equals("close")){v.closeContainer();return;}if(a.equals("back")){AdminMenu.open(v);return;}if(a.equals("players")){openPlayers(v);return;}if(a.equals("economy")){openEconomy(v);return;}if(a.equals("claims")){openClaims(v);return;}if(a.equals("shops")){openShops(v);return;}if(a.equals("kits")){openKits(v);return;}if(a.equals("moderation")){openModeration(v);return;}if(a.equals("wanderlog")){openWanderlog(v);return;}
  if(a.startsWith("confirm:")){String real=a.substring(8);if(real.equals(CONFIRM.remove(v.getUUID()))){ItemStack fake=new ItemStack(Items.PAPER);fake.getOrCreateTag().putString("KivraAdminAction",real);handleClick(v,fake);}return;}
  if(a.startsWith("player:")){ServerPlayer t=find(v,a.substring(7));if(t!=null)openPlayer(v,t);return;}if(a.startsWith("ranks:")){ServerPlayer t=find(v,a.substring(6));if(t!=null)openRanks(v,t);return;}
  if(a.startsWith("rank:")){String[]p=a.split(":",3);ServerPlayer t=p.length==3?find(v,p[1]):null;if(t==null)return;String g=p[2];if(g.equalsIgnoreCase("default")){say(v,"Default is inherited automatically.");openRanks(v,t);return;}boolean on=Kivra.permissions().effectiveGroups(t.getUUID()).contains(g),ok=on?Kivra.permissions().removeGroup(t.getUUID(),g):Kivra.permissions().addGroup(t.getUUID(),g);say(v,ok?(on?"Removed ":"Added ")+g+" for "+t.getGameProfile().getName():"Could not change rank.");openRanks(v,t);return;}
  if(a.startsWith("econplayer:")){ServerPlayer t=find(v,a.substring(11));if(t!=null)openEconomyPlayer(v,t);return;}if(a.startsWith("econ:")){String[]p=a.split(":",4);ServerPlayer t=p.length>=3?find(v,p[2]):null;if(t==null)return;BigDecimal n=p.length==4?new BigDecimal(p[3]):BigDecimal.ZERO;boolean ok=switch(p[1]){case"add"->Kivra.economy().deposit(t.getUUID(),n);case"take"->Kivra.economy().withdraw(t.getUUID(),n);case"zero"->Kivra.economy().set(t.getUUID(),BigDecimal.ZERO);default->false;};say(v,ok?"Balance updated.":"Could not update balance.");openEconomyPlayer(v,t);return;}
  if(a.startsWith("claimowner:")){ServerPlayer t=find(v,a.substring(11));if(t!=null)openClaimsPlayer(v,t);return;}if(a.startsWith("claimask:")){confirm(v,a.substring(9),"Delete this claim permanently?");return;}if(a.startsWith("claimdel:")){String name=a.substring(9);boolean ok=Kivra.claims().delete(v,name,true);say(v,ok?"Claim deleted: "+name:"Could not delete claim.");openClaims(v);return;}
  if(a.startsWith("shopask:")){confirm(v,a.substring(8),"Delete this shop permanently?");return;}if(a.startsWith("shopdel:")){String name=a.substring(8);boolean ok=Kivra.shops().delete(v,name,true);say(v,ok?"Shop deleted: "+name:"Could not delete shop.");openShops(v);return;}
  if(a.startsWith("kitgive:")){String[]p=a.split(":",3);ServerPlayer t=p.length==3?find(v,p[1]):null;if(t!=null){boolean ok=Kivra.kits().give(t,p[2],true);say(v,ok?"Kit "+p[2]+" given to "+t.getGameProfile().getName():"Could not give kit.");openKits(v);}return;}if(a.startsWith("kitask:")){confirm(v,a.substring(7),"Delete this kit permanently?");return;}if(a.startsWith("kitdel:")){String n=a.substring(7);boolean ok=Kivra.kits().delete(n);say(v,ok?"Kit deleted: "+n:"Could not delete kit.");openKits(v);return;}if(a.startsWith("kit:")){openKit(v,a.substring(4));return;}
  if(a.startsWith("wanderplayer:")){ServerPlayer t=find(v,a.substring(13));if(t!=null)openWanderlogPlayer(v,t);return;}if(a.startsWith("modplayer:")){ServerPlayer t=find(v,a.substring(10));if(t!=null)openModerationPlayer(v,t);return;}if(a.startsWith("mod:")){String[]p=a.split(":",3);ServerPlayer t=p.length==3?find(v,p[2]):null;if(t==null)return;UUID s=v.getUUID();switch(p[1]){case"warn"->Kivra.moderation().warn(t.getUUID(),t.getGameProfile().getName(),s,"GUI warning by "+v.getGameProfile().getName());case"mute"->Kivra.moderation().mute(t.getUUID(),t.getGameProfile().getName(),s,"GUI mute by "+v.getGameProfile().getName(),3600000L);case"unmute"->Kivra.moderation().unmute(t.getUUID(),s);case"unban"->Kivra.moderation().unban(t.getUUID(),s);}openModerationPlayer(v,t);}
 }
 private static boolean admin(ServerPlayer v){return v.hasPermissions(4)||Kivra.permissions().hasPermission(v,"kivra.admin");}private static ServerPlayer find(ServerPlayer v,String u){try{return v.getServer().getPlayerList().getPlayer(UUID.fromString(u));}catch(Exception e){return null;}}private static void say(ServerPlayer v,String s){v.sendSystemMessage(Component.literal(s));}
 private static void confirm(ServerPlayer v,String action,String text){CONFIRM.put(v.getUUID(),action);v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);button(m,11,Items.LIME_DYE,"Confirm",text,"confirm:"+action);button(m,15,Items.RED_DYE,"Cancel","Return to main admin menu","back");return m;},Component.literal("Kivra - Confirm action")));}
 public static void openPlayers(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;PermissionGroup r=Kivra.permissions().primaryGroup(t.getUUID());button(m,s++,Items.PLAYER_HEAD,t.getGameProfile().getName(),"Rank: "+(r==null?"default":r.name()),"player:"+t.getUUID());}back(m,"back");return m;},Component.literal("Kivra Admin - Players")));}
 public static void openRanksOverview(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);List<PermissionGroup>g=new ArrayList<>(Kivra.permissions().groups());g.sort(Comparator.comparingInt(PermissionGroup::weight).reversed());int s=0;for(PermissionGroup r:g){if(s>=45)break;button(m,s++,Items.NAME_TAG,r.name(),"Weight "+r.weight()+" | parents: "+String.join(", ",r.parents()),"noop");}back(m,"back");return m;},Component.literal("Kivra Admin - Ranks")));}
 public static void openPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);PermissionGroup r=Kivra.permissions().primaryGroup(t.getUUID());button(m,10,Items.PLAYER_HEAD,t.getGameProfile().getName(),"Primary: "+(r==null?"default":r.name()),"noop");button(m,12,Items.NAME_TAG,"Change Rank","Open selector","ranks:"+t.getUUID());button(m,14,Items.PAPER,"Permissions","Groups: "+String.join(", ",Kivra.permissions().effectiveGroups(t.getUUID())),"noop");button(m,16,Items.ARROW,"Back","Players","players");return m;},Component.literal("Kivra - "+t.getGameProfile().getName())));}
 public static void openRanks(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);List<PermissionGroup>g=new ArrayList<>(Kivra.permissions().groups());g.sort(Comparator.comparingInt(PermissionGroup::weight).reversed());int s=0;for(PermissionGroup r:g){if(s>=45)break;boolean on=Kivra.permissions().effectiveGroups(t.getUUID()).contains(r.name());button(m,s++,on?Items.LIME_DYE:Items.GRAY_DYE,r.name(),on?"Assigned":"Not assigned","rank:"+t.getUUID()+":"+r.name());}button(m,49,Items.ARROW,"Back","Player","player:"+t.getUUID());return m;},Component.literal("Kivra Ranks - "+t.getGameProfile().getName())));}
 public static void openEconomy(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;button(m,s++,Items.GOLD_INGOT,t.getGameProfile().getName(),Kivra.economy().format(Kivra.economy().balance(t.getUUID())),"econplayer:"+t.getUUID());}back(m,"back");return m;},Component.literal("Kivra Admin - Economy")));}
 public static void openEconomyPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);button(m,10,Items.GOLD_INGOT,"Balance",Kivra.economy().format(Kivra.economy().balance(t.getUUID())),"noop");button(m,12,Items.LIME_DYE,"+100","Deposit","econ:add:"+t.getUUID()+":100");button(m,13,Items.LIME_DYE,"+1000","Deposit","econ:add:"+t.getUUID()+":1000");button(m,14,Items.RED_DYE,"-100","Withdraw","econ:take:"+t.getUUID()+":100");button(m,15,Items.BARRIER,"Set 0","Reset","econ:zero:"+t.getUUID());button(m,16,Items.ARROW,"Back","Economy","economy");return m;},Component.literal("Economy - "+t.getGameProfile().getName())));}
 public static void openClaims(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){Set<String>o=Kivra.claims().owned(t.getUUID());if(o.isEmpty())continue;if(s>=45)break;button(m,s++,Items.GOLDEN_SHOVEL,t.getGameProfile().getName(),o.size()+" claims","claimowner:"+t.getUUID());}back(m,"back");return m;},Component.literal("Kivra Admin - Claims")));}
 public static void openClaimsPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(String n:Kivra.claims().owned(t.getUUID())){if(s>=45)break;button(m,s++,Items.MAP,n,"Click to delete claim","claimask:claimdel:"+n);}button(m,49,Items.ARROW,"Back","Claims","claims");return m;},Component.literal("Claims - "+t.getGameProfile().getName())));}
 public static void openShops(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(String n:Kivra.shops().names()){if(s>=45)break;button(m,s++,Items.EMERALD,n,Kivra.shops().describe(n)+" | click to delete","shopask:shopdel:"+n);}back(m,"back");return m;},Component.literal("Kivra Admin - Shops")));}
 public static void openKits(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(String n:Kivra.kits().names()){if(s>=45)break;button(m,s++,Items.CHEST,n,"Open kit actions","kit:"+n);}back(m,"back");return m;},Component.literal("Kivra Admin - Kits")));}
 public static void openKit(ServerPlayer v,String n){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;button(m,s++,Items.PLAYER_HEAD,"Give to "+t.getGameProfile().getName(),"Bypass cooldown","kitgive:"+t.getUUID()+":"+n);}button(m,47,Items.BARRIER,"Delete Kit","Delete "+n,"kitask:kitdel:"+n);button(m,49,Items.ARROW,"Back","Kits","kits");return m;},Component.literal("Kit - "+n)));}
 public static void openWanderlog(ServerPlayer v){if(!WanderlogIntegration.isLoaded()){say(v,"Wanderlog is not installed.");AdminMenu.open(v);return;}v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;WanderlogIntegration.Stats st=WanderlogIntegration.stats(v.getServer(),t.getUUID());String d=st==null?"No Wanderlog data":"Level "+st.level()+" | XP "+st.xp()+"/"+st.xpForNextLevel()+" | Biomes "+st.discoveredBiomes();button(m,s++,Items.COMPASS,t.getGameProfile().getName(),d,"wanderplayer:"+t.getUUID());}back(m,"back");return m;},Component.literal("Kivra Admin - Wanderlog")));}
 public static void openWanderlogPlayer(ServerPlayer v,ServerPlayer t){WanderlogIntegration.Stats st=WanderlogIntegration.stats(v.getServer(),t.getUUID());v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);if(st==null){button(m,13,Items.BARRIER,"No Wanderlog data","No stats available for this player","noop");}else{button(m,10,Items.COMPASS,"Explorer Level",String.valueOf(st.level()),"noop");button(m,12,Items.EXPERIENCE_BOTTLE,"Explorer XP",st.xp()+" / "+st.xpForNextLevel(),"noop");button(m,14,Items.MAP,"Discovered Biomes",String.valueOf(st.discoveredBiomes()),"noop");}button(m,16,Items.ARROW,"Back","Wanderlog players","wanderlog");return m;},Component.literal("Wanderlog - "+t.getGameProfile().getName())));}
 public static void openModeration(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;button(m,s++,Items.IRON_SWORD,t.getGameProfile().getName(),"History: "+Kivra.moderation().history(t.getUUID()).size(),"modplayer:"+t.getUUID());}back(m,"back");return m;},Component.literal("Kivra Admin - Moderation")));}
 public static void openModerationPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);List<Record>h=Kivra.moderation().history(t.getUUID());button(m,10,Items.PAPER,"History",h.size()+" entries","noop");button(m,12,Items.PAPER,"Warn","Add warning","mod:warn:"+t.getUUID());boolean mu=Kivra.moderation().mute(t.getUUID())!=null;button(m,13,mu?Items.LIME_DYE:Items.RED_DYE,mu?"Unmute":"Mute 1h",mu?"Remove mute":"Mute one hour",(mu?"mod:unmute:":"mod:mute:")+t.getUUID());boolean b=Kivra.moderation().ban(t.getUUID())!=null;button(m,14,b?Items.LIME_DYE:Items.GRAY_DYE,b?"Unban":"Not banned",b?"Remove ban":"No active ban",b?"mod:unban:"+t.getUUID():"noop");button(m,16,Items.ARROW,"Back","Moderation","moderation");return m;},Component.literal("Moderation - "+t.getGameProfile().getName())));}
 private static void back(ChestMenu m,String a){button(m,49,Items.ARROW,"Back","Return",a);}static void button(ChestMenu m,int s,net.minecraft.world.item.Item it,String n,String d,String a){ItemStack st=new ItemStack(it);st.setHoverName(Component.literal(n));st.getOrCreateTag().putString("KivraAdminAction",a);st.getOrCreateTag().putString("KivraAdminDescription",d);m.getContainer().setItem(s,st);}
}
