package dev.nazhida.kivra.admin;

import dev.nazhida.kivra.Kivra;
import dev.nazhida.kivra.moderation.ModerationService.Record;
import dev.nazhida.kivra.permissions.PermissionGroup;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.SimpleMenuProvider;
import net.minecraft.world.inventory.ChestMenu;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import java.math.BigDecimal;
import java.util.*;

public final class AdminMenuEvents {
    public static void handleClick(ServerPlayer viewer,ItemStack clicked){
        if(clicked.isEmpty()||!clicked.hasTag())return;String action=clicked.getOrCreateTag().getString("KivraAdminAction");if(action.isBlank()||action.equals("noop"))return;
        if(action.equals("Players")){openPlayers(viewer);return;}if(action.equals("Ranks & Permissions")){openRanksOverview(viewer);return;}if(action.equals("Economy")){openEconomy(viewer);return;}if(action.equals("Moderation")){openModeration(viewer);return;}if(action.equals("Close")||action.equals("close")){viewer.closeContainer();return;}if(action.equals("back")){AdminMenu.open(viewer);return;}if(action.equals("players")){openPlayers(viewer);return;}
        if(action.startsWith("player:")){ServerPlayer t=find(viewer,action.substring(7));if(t!=null)openPlayer(viewer,t);return;}if(action.startsWith("ranks:")){ServerPlayer t=find(viewer,action.substring(6));if(t!=null)openRanks(viewer,t);return;}
        if(action.startsWith("rank:")){String[]p=action.split(":",3);if(p.length!=3)return;ServerPlayer t=find(viewer,p[1]);if(t==null)return;String g=p[2];if(g.equalsIgnoreCase("default")){viewer.sendSystemMessage(Component.literal("The default rank is inherited automatically."));openRanks(viewer,t);return;}boolean active=Kivra.permissions().effectiveGroups(t.getUUID()).contains(g);boolean ok=active?Kivra.permissions().removeGroup(t.getUUID(),g):Kivra.permissions().addGroup(t.getUUID(),g);viewer.sendSystemMessage(Component.literal(ok?(active?"Removed ":"Added ")+g+" for "+t.getGameProfile().getName():"Could not change rank."));openRanks(viewer,t);return;}
        if(action.startsWith("econplayer:")){ServerPlayer t=find(viewer,action.substring(11));if(t!=null)openEconomyPlayer(viewer,t);return;}if(action.equals("economy")){openEconomy(viewer);return;}
        if(action.startsWith("econ:")){String[]p=action.split(":",4);if(p.length<3)return;ServerPlayer t=find(viewer,p[2]);if(t==null)return;BigDecimal amount=p.length==4?new BigDecimal(p[3]):BigDecimal.ZERO;boolean ok=switch(p[1]){case "add"->Kivra.economy().deposit(t.getUUID(),amount);case "take"->Kivra.economy().withdraw(t.getUUID(),amount);case "zero"->Kivra.economy().set(t.getUUID(),BigDecimal.ZERO);default->false;};viewer.sendSystemMessage(Component.literal(ok?"Balance updated.":"Could not update balance."));openEconomyPlayer(viewer,t);return;}
        if(action.startsWith("modplayer:")){ServerPlayer t=find(viewer,action.substring(10));if(t!=null)openModerationPlayer(viewer,t);return;}if(action.equals("moderation")){openModeration(viewer);return;}
        if(action.startsWith("mod:")){String[]p=action.split(":",3);if(p.length!=3)return;ServerPlayer t=find(viewer,p[2]);if(t==null)return;UUID staff=viewer.getUUID();switch(p[1]){case "warn"->Kivra.moderation().warn(t.getUUID(),t.getGameProfile().getName(),staff,"GUI warning by "+viewer.getGameProfile().getName());case "mute"->Kivra.moderation().mute(t.getUUID(),t.getGameProfile().getName(),staff,"GUI mute by "+viewer.getGameProfile().getName(),3600000L);case "unmute"->Kivra.moderation().unmute(t.getUUID(),staff);case "unban"->Kivra.moderation().unban(t.getUUID(),staff);}openModerationPlayer(viewer,t);}
    }
    private static ServerPlayer find(ServerPlayer v,String raw){try{return v.getServer().getPlayerList().getPlayer(UUID.fromString(raw));}catch(Exception e){return null;}}
    public static void openPlayers(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;PermissionGroup r=Kivra.permissions().primaryGroup(t.getUUID());button(m,s++,Items.PLAYER_HEAD,t.getGameProfile().getName(),"Rank: "+(r==null?"default":r.name()),"player:"+t.getUUID());}button(m,49,Items.ARROW,"Back","Main menu","back");return m;},Component.literal("Kivra Admin - Players")));}
    public static void openRanksOverview(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);List<PermissionGroup>gs=new ArrayList<>(Kivra.permissions().groups());gs.sort(Comparator.comparingInt(PermissionGroup::weight).reversed());int s=0;for(PermissionGroup g:gs){if(s>=45)break;button(m,s++,Items.NAME_TAG,g.name(),"Weight "+g.weight()+" | parents: "+String.join(", ",g.parents()),"noop");}button(m,49,Items.ARROW,"Back","Main menu","back");return m;},Component.literal("Kivra Admin - Ranks")));}
    public static void openPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);PermissionGroup r=Kivra.permissions().primaryGroup(t.getUUID());button(m,10,Items.PLAYER_HEAD,t.getGameProfile().getName(),"Primary rank: "+(r==null?"default":r.name()),"noop");button(m,12,Items.NAME_TAG,"Change Rank","Open rank selector","ranks:"+t.getUUID());button(m,14,Items.PAPER,"Permissions","Groups: "+String.join(", ",Kivra.permissions().effectiveGroups(t.getUUID())),"noop");button(m,16,Items.ARROW,"Back","Players","players");return m;},Component.literal("Kivra - "+t.getGameProfile().getName())));}
    public static void openRanks(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);List<PermissionGroup>gs=new ArrayList<>(Kivra.permissions().groups());gs.sort(Comparator.comparingInt(PermissionGroup::weight).reversed());int s=0;for(PermissionGroup g:gs){if(s>=45)break;boolean a=Kivra.permissions().effectiveGroups(t.getUUID()).contains(g.name());button(m,s++,a?Items.LIME_DYE:Items.GRAY_DYE,g.name(),(a?"Assigned":"Not assigned")+" | weight "+g.weight(),"rank:"+t.getUUID()+":"+g.name());}button(m,49,Items.ARROW,"Back","Player","player:"+t.getUUID());return m;},Component.literal("Kivra Ranks - "+t.getGameProfile().getName())));}
    public static void openEconomy(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;button(m,s++,Items.GOLD_INGOT,t.getGameProfile().getName(),"Balance: "+Kivra.economy().format(Kivra.economy().balance(t.getUUID())),"econplayer:"+t.getUUID());}button(m,49,Items.ARROW,"Back","Main menu","back");return m;},Component.literal("Kivra Admin - Economy")));}
    public static void openEconomyPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);button(m,10,Items.GOLD_INGOT,"Balance",Kivra.economy().format(Kivra.economy().balance(t.getUUID())),"noop");button(m,12,Items.LIME_DYE,"+100","Deposit 100 coins","econ:add:"+t.getUUID()+":100");button(m,13,Items.LIME_DYE,"+1000","Deposit 1000 coins","econ:add:"+t.getUUID()+":1000");button(m,14,Items.RED_DYE,"-100","Withdraw 100 coins","econ:take:"+t.getUUID()+":100");button(m,15,Items.BARRIER,"Set 0","Reset balance","econ:zero:"+t.getUUID());button(m,16,Items.ARROW,"Back","Economy players","economy");return m;},Component.literal("Economy - "+t.getGameProfile().getName())));}
    public static void openModeration(ServerPlayer v){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.sixRows(id,i);int s=0;for(ServerPlayer t:v.getServer().getPlayerList().getPlayers()){if(s>=45)break;button(m,s++,Items.IRON_SWORD,t.getGameProfile().getName(),"History: "+Kivra.moderation().history(t.getUUID()).size()+" entries","modplayer:"+t.getUUID());}button(m,49,Items.ARROW,"Back","Main menu","back");return m;},Component.literal("Kivra Admin - Moderation")));}
    public static void openModerationPlayer(ServerPlayer v,ServerPlayer t){v.openMenu(new SimpleMenuProvider((id,i,x)->{AdminChestMenu m=AdminChestMenu.threeRows(id,i);List<Record> h=Kivra.moderation().history(t.getUUID());button(m,10,Items.PAPER,"History",h.size()+" entries","noop");button(m,12,Items.PAPER,"Warn","Add GUI warning","mod:warn:"+t.getUUID());boolean muted=Kivra.moderation().mute(t.getUUID())!=null;button(m,13,muted?Items.LIME_DYE:Items.RED_DYE,muted?"Unmute":"Mute 1h",muted?"Remove active mute":"Mute for one hour",(muted?"mod:unmute:":"mod:mute:")+t.getUUID());boolean banned=Kivra.moderation().ban(t.getUUID())!=null;button(m,14,banned?Items.LIME_DYE:Items.GRAY_DYE,banned?"Unban":"Not banned",banned?"Remove active ban":"No active ban",banned?"mod:unban:"+t.getUUID():"noop");button(m,16,Items.ARROW,"Back","Moderation players","moderation");return m;},Component.literal("Moderation - "+t.getGameProfile().getName())));}
    static void button(ChestMenu m,int s,net.minecraft.world.item.Item item,String n,String d,String a){ItemStack st=new ItemStack(item);st.setHoverName(Component.literal(n));st.getOrCreateTag().putString("KivraAdminAction",a);st.getOrCreateTag().putString("KivraAdminDescription",d);m.getContainer().setItem(s,st);}
}
